package Paquete.Pojos;
// Generated 1/07/2019 07:23:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  {


     private int idMaterial;
     private String nombre;
     private int cantidad;
     private short existenciaInventario;
     private String caracteristicas;
     private Set deudas = new HashSet(0);
     private Set datosVales = new HashSet(0);
     private Set materialUtilizados = new HashSet(0);

    public Material() {
    }

	
    public Material(int idMaterial, String nombre, int cantidad, short existenciaInventario, String caracteristicas) {
        this.idMaterial = idMaterial;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.existenciaInventario = existenciaInventario;
        this.caracteristicas = caracteristicas;
    }
    public Material(int idMaterial, String nombre, int cantidad, short existenciaInventario, String caracteristicas, Set deudas, Set datosVales, Set materialUtilizados) {
       this.idMaterial = idMaterial;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.existenciaInventario = existenciaInventario;
       this.caracteristicas = caracteristicas;
       this.deudas = deudas;
       this.datosVales = datosVales;
       this.materialUtilizados = materialUtilizados;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public short getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(short existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }
    public Set getDatosVales() {
        return this.datosVales;
    }
    
    public void setDatosVales(Set datosVales) {
        this.datosVales = datosVales;
    }
    public Set getMaterialUtilizados() {
        return this.materialUtilizados;
    }
    
    public void setMaterialUtilizados(Set materialUtilizados) {
        this.materialUtilizados = materialUtilizados;
    }




}


