package Paquete.Pojos;
// Generated 1/07/2019 07:23:53 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Reactivos generated by hbm2java
 */
public class Reactivos  implements java.io.Serializable {


     private int idReactivo;
     private String nombre;
     private String tipo;
     private double cantidad;
     private byte existenciaInventario;
     private String medida;
     private Set datosVales = new HashSet(0);
     private Set reactivoUtilizados = new HashSet(0);
     private Set reactivosUtilizadoPracticas = new HashSet(0);

    public Reactivos() {
    }

	
    public Reactivos(int idReactivo, String nombre, String tipo, double cantidad, byte existenciaInventario, String medida) {
        this.idReactivo = idReactivo;
        this.nombre = nombre;
        this.tipo = tipo;
        this.cantidad = cantidad;
        this.existenciaInventario = existenciaInventario;
        this.medida = medida;
    }
    public Reactivos(int idReactivo, String nombre, String tipo, double cantidad, byte existenciaInventario, String medida, Set datosVales, Set reactivoUtilizados, Set reactivosUtilizadoPracticas) {
       this.idReactivo = idReactivo;
       this.nombre = nombre;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.existenciaInventario = existenciaInventario;
       this.medida = medida;
       this.datosVales = datosVales;
       this.reactivoUtilizados = reactivoUtilizados;
       this.reactivosUtilizadoPracticas = reactivosUtilizadoPracticas;
    }
   
    public int getIdReactivo() {
        return this.idReactivo;
    }
    
    public void setIdReactivo(int idReactivo) {
        this.idReactivo = idReactivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public byte getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(byte existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }
    public Set getDatosVales() {
        return this.datosVales;
    }
    
    public void setDatosVales(Set datosVales) {
        this.datosVales = datosVales;
    }
    public Set getReactivoUtilizados() {
        return this.reactivoUtilizados;
    }
    
    public void setReactivoUtilizados(Set reactivoUtilizados) {
        this.reactivoUtilizados = reactivoUtilizados;
    }
    public Set getReactivosUtilizadoPracticas() {
        return this.reactivosUtilizadoPracticas;
    }
    
    public void setReactivosUtilizadoPracticas(Set reactivosUtilizadoPracticas) {
        this.reactivosUtilizadoPracticas = reactivosUtilizadoPracticas;
    }




}


