package Paquete.Pojos;
// Generated 1/07/2019 07:23:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int idrol;
     private String nombreRol;
     private Set usuarioses = new HashSet(0);
     private Set usuarioses_1 = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int idrol, String nombreRol) {
        this.idrol = idrol;
        this.nombreRol = nombreRol;
    }
    public Roles(int idrol, String nombreRol, Set usuarioses, Set usuarioses_1) {
       this.idrol = idrol;
       this.nombreRol = nombreRol;
       this.usuarioses = usuarioses;
       this.usuarioses_1 = usuarioses_1;
    }
   
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getUsuarioses_1() {
        return this.usuarioses_1;
    }
    
    public void setUsuarioses_1(Set usuarioses_1) {
        this.usuarioses_1 = usuarioses_1;
    }




}


